apiVersion: security.accuknox.com/v1
kind: KubeArmorPolicy
metadata:
  name: mitre-tactic-persistence
spec:
  selectorLabels:
      nodeSelector:
          hostname: xyz
  process: 
        matchPaths: 
        - path: /etc/ssh/sshd_config
        - path: ~/. ssh/authorized_keys
  action:
    Block
  severity: 4 