apiVersion: security.accuknox.com/v1
kind: KubeArmorPolicy
metadata:
  name: mitre-tactic-persistence
spec:
  selectorLabels:
      nodeSelector:
          hostname: xyz
  process: 
        matchPaths: 
        - path: /bin/grep
          onDirectory: 
          - path: /etc/xdg/autostart
        matchPaths: 
        - path: /bin/cat
          onDirectory: 
          - path: ~/.config/autostart  
  action:
    Audit & Block
  severity: 5 